config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  # Number of posts to show in each page
  self.per_page = 4
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "New post was successfully created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "The post was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    if @post.delete
      redirect_to posts_path, notice: "The post was successfully deleted!"
    else
      render 'edit'
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:author, :title, :category_id, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Used to set the active class in current page (Navbar)
  def active_class?(current_path)
    class_name = request.path == current_path ? 'nav-item nav-link active' : 'nav-item nav-link'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Blog System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Simple Blog System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mr-auto">
          <%= link_to "Home", root_path, class: active_class?(root_path) %>
          <%= link_to "Posts", posts_path, class: active_class?(posts_path) %>
        </div>
        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%= link_to "Logout",
                        destroy_user_session_path,
                        method: :delete,
                        class: 'nav-item nav-link' %>
          <% else %>
            <%= link_to "Login",
                        new_user_session_path,
                        class: 'nav-item nav-link' %>
            <%= link_to "Register",
                        new_user_registration_path,
                        class: 'nav-item nav-link' %>
          <% end %>
        </div>
      </div>
    </nav>
    <% if notice %>
      <div class="alert alert-dark alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="header">
    <div class="row">
      <div class="col-12 text-center">
        <h2>Welcome, to our Blog System!</h2>
      </div>
    </div>
  </div>
  <hr>
  <div class="blog-categories text-center">
    <div class="row">
      <div class="col-12">
        <h3>Blog Categories</h3>
      </div>
    </div>
    <div class="row">
      <% @categories.each do |category| %>
        <div class="col-2">
          <p><%= category.name %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <div class="field form-group">
    <%= f.label (:author) %>
    <%= f.text_field (:author), class: 'form-control', readonly: true, value: current_user.full_name %>
  </div>
  <div class="field form-group">
    <%= f.label (:title) %>
    <%= f.text_field (:title), class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label (:category_id) %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, { class: 'form-control' }) %>
  </div>
  <div class="field form-group">
    <%= f.label (:content) %>
    <%= f.text_area (:content), class: 'form-control' %>
  </div>
  <div class="actions">
    <%= link_to  "Back", "/posts/", class: 'btn btn-primary' %>
    <%= f.submit class: 'btn btn-success' %>
    <% if request.path.include? "edit" %>
      <%= link_to  "Delete Post", post_path,
                    method: :delete,
                    data: { confirm: "That action can't be undone! Are you sure?" },
                    class: 'btn btn-danger' %>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="header">
    <div class="row">
      <div class="col-12 text-center">
        <h2>Edit Post</h2>
      </div>
    </div>
  </div>
  <hr>

  <%= render "form", post: @post %>

</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="header">
    <div class="row">
      <div class="col-12 text-center">
        <h2>Posts</h2>
        <% if user_signed_in? %>
        <div class="actions text-right">
          <%= link_to '<i class="fas fa-pencil-alt text-dark"></i> New Post'.html_safe,
              new_post_path,
              class: 'text-dark' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <div class="row posts">
      <% @posts.each do |post| %>
      <div class="col-md-12 col-lg-6">
        <div class="card">
          <div class="card-body">
            <div class="post-title text-center">
              <h3><%= link_to post.title, post %></h3>
            </div>
            <div class="post-meta text-center">
              <small><i class="fas fa-user"></i> <%= post.author %></small> |
              <small><i class="fas fa-tags"></i> <%= post.category.name %></small> |
              <small><i class="fas fa-clock"></i> Posted at: <%= post.created_at.strftime("%d.%m.%Y %H:%M") %></small>
            </div>
            <hr>
            <div class="post-content text-justify">
              <p>
                <%= post.content.size > 60 ? 
                  post.content.slice(0..60) + "..." : 
                  post.content %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>
  <%= will_paginate @posts, class: 'text-center' %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="header">
    <div class="row">
      <div class="col-12 text-center">
        <h2>New Post</h2>
      </div>
    </div>
  </div>
  <hr>

  <%= form_for( @post , remote: true) do |f| %>
    <div class="field form-group">
      <%= f.label (:author) %>
      <%= f.text_field (:author), class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label (:title) %>
      <%= f.text_field (:title), class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label (:category) %>
      <%= f.text_field (:category), class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label (:content) %>
      <%= f.text_area (:content), class: 'form-control' %>
    </div>
    <%= f.submit "Create Post", class: 'btn btn-success' %>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="header">
    <div class="row">
      <div class="col-12 text-center">
        <h2><%= @post.title %></h2>
      </div>
    </div>
  </div>
  <hr>

  <div class="post-content">
    <div class="row">
      <div class="col-12">
        <%= simple_format(@post.content, class: 'lead') %>
      </div>
    </div>
  </div>

  <hr>

  <div class="post-meta text-center">
    <div class="row">
      <div class="col-3"><i class="fas fa-user"></i> Author: <%= @post.author %></div>
      <div class="col-3"><i class="fas fa-tags"></i> Category: <%= @post.category.name %></div>
      <div class="col-3"><i class="fas fa-clock"></i> Posted at: <%= @post.created_at.strftime("%d.%m.%Y %H:%M") %></div>
      <div class="col-3"><%= link_to  "Edit Post", edit_post_path, class: 'btn btn-warning' %></div>
    </div>
  </div>

</div>